# Generated by Django 4.0.5 on 2022-11-21 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('planoid', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('ot', models.IntegerField()),
                ('vendedor', models.CharField(max_length=100)),
                ('cliente', models.CharField(max_length=100)),
                ('obra', models.CharField(max_length=100)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Estandar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(unique=True)),
                ('imagen', models.ImageField(upload_to='imagenes')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('ancho_mm', models.IntegerField()),
                ('alto_mm', models.IntegerField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.estandar')),
                ('planoid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.plano')),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=100)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.estandar')),
            ],
        ),
        migrations.AddConstraint(
            model_name='comentarios',
            constraint=models.UniqueConstraint(fields=('codigo', 'comentario'), name='unique_comentario'),
        ),
    ]
