# Generated by Django 4.0.5 on 2022-07-07 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estandar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ComentariosEstandar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerolinea', models.IntegerField()),
                ('comentario', models.CharField(max_length=20)),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.estandar')),
            ],
        ),
    ]
