# Generated by Django 4.0.5 on 2022-12-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_alter_detalleplano_alto_mm_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='detalleplano',
            constraint=models.UniqueConstraint(fields=('planoid', 'codigo', 'tipo', 'ancho_mm', 'alto_mm', 'comentario'), name='all_unique'),
        ),
    ]
