# Generated by Django 4.0.5 on 2022-07-28 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_remove_estandar_image_estandar_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=100)),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.estandar')),
            ],
        ),
        migrations.DeleteModel(
            name='ComentariosEstandar',
        ),
    ]
