# Generated by Django 4.0.5 on 2022-11-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_remove_plano_cliente_remove_plano_obra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleplano',
            name='tipo',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
