# Generated by Django 4.0.5 on 2022-08-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_comentarios_delete_comentariosestandar'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='comentarios',
            constraint=models.UniqueConstraint(fields=('codigo', 'comentario'), name='unique_comentario'),
        ),
        migrations.AddConstraint(
            model_name='estandar',
            constraint=models.UniqueConstraint(fields=('codigo',), name='unique_codigo'),
        ),
    ]
