# Generated by Django 4.0.5 on 2022-12-13 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_detalleplano_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estandar',
            name='imagen',
            field=models.ImageField(upload_to='imagenes/estandar'),
        ),
    ]
