# Generated by Django 4.0.5 on 2022-12-21 22:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_detalleplano_all_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleplano',
            name='comentario',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='plano',
            name='ot',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
