# Generated by Django 4.0.5 on 2022-08-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_comentarios_unique_comentario_estandar_unique_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estandar',
            name='codigo',
            field=models.SlugField(),
        ),
    ]
