# Generated by Django 4.0.5 on 2022-12-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_alter_detalleplano_comentario_alter_plano_ot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15, unique=True)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
    ]
