# Generated by Django 4.0.5 on 2022-12-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_alter_estandar_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='ultima_generacion_imagen',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
