# Generated by Django 3.2.14 on 2022-11-04 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_categoria_estandar_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='estandar',
            name='unique_codigo',
        ),
        migrations.AlterField(
            model_name='estandar',
            name='codigo',
            field=models.SlugField(unique=True),
        ),
        migrations.AddField(
            model_name='plano',
            name='codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.estandar'),
        ),
    ]
