# Generated by Django 4.0.5 on 2022-12-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0007_alter_plano_ultima_generacion_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='ultima_generacion_imagen',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
