# Generated by Django 4.0.5 on 2022-12-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0008_alter_plano_ultima_generacion_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleplano',
            name='autor',
        ),
        migrations.AddField(
            model_name='detalleplano',
            name='comentario',
            field=models.TextField(default=None, null=True),
        ),
    ]
