# Generated by Django 4.0.5 on 2022-12-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0009_remove_detalleplano_autor_detalleplano_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleplano',
            name='comentario',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
